#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### COLORS (Theme) #####
BAR_COLOR=0xff0b1d2a
ITEM_COLOR=0xff7dd3fc
SUBTLE_COLOR=0xff5b7083
ACTIVE_BG=0xff1e3a5f
INACTIVE_BG=0x30293b4a

##### BAR APPEARANCE #####
sketchybar --bar \
  position=top \
  height=30 \
  sticky=on \
  blur_radius=25 \
  padding_left=12 \
  padding_right=12 \
  color=$BAR_COLOR

##### DEFAULT ITEM STYLE #####
default=(
  icon.font="JetBrainsMono Nerd Font:Bold:14.0"
  label.font="JetBrainsMono Nerd Font:Bold:13.0"
  icon.color=$ITEM_COLOR
  label.color=$ITEM_COLOR
  background.color=$INACTIVE_BG
  background.corner_radius=6
  background.height=24
  padding_left=6
  padding_right=6
  icon.padding_left=5
  icon.padding_right=5
  label.padding_left=6
  label.padding_right=6
)
sketchybar --default "${default[@]}"

##### SPACES (Mission Control) #####
SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")

for i in "${!SPACE_ICONS[@]}"; do
  sid="$((i+1))"
  sketchybar --add space space.$sid left \
    --set space.$sid \
      space=$sid \
      icon="${SPACE_ICONS[i]}" \
      label.drawing=off \
      background.color=$INACTIVE_BG \
      background.corner_radius=6 \
      background.height=24 \
      icon.color=$SUBTLE_COLOR \
      script="$PLUGIN_DIR/space.sh" \
      click_script="yabai -m space --focus $sid"
done

##### LEFT ITEMS #####
sketchybar \
  --add item apple left \
  --set apple \
    icon= \
    label.drawing=off \
    icon.font="JetBrainsMono Nerd Font:Bold:16.0" \
    icon.color=$ITEM_COLOR \
  --add item front_app left \
  --set front_app \
    icon.drawing=off \
    label.color=$ITEM_COLOR \
    script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app front_app_switched

##### RIGHT ITEMS #####
sketchybar \
  --add item volume right \
  --set volume \
    icon=󰕾 \
    script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change \
  --add item battery right \
  --set battery \
    icon=󰁹 \
    update_freq=120 \
    script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change \
  --add item clock right \
  --set clock \
    icon=󰥔 \
    update_freq=10 \
    script="$PLUGIN_DIR/clock.sh"

##### INITIAL UPDATE #####
sketchybar --update
